/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PractitionerSpaceRouteImport } from './routes/practitioner-space'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsIdRouteImport } from './routes/therapists.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated.chat.$threadId'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated.app.history'
import { Route as AuthenticatedAppAssessmentRouteImport } from './routes/_authenticated.app.assessment'

const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerSpaceRoute = PractitionerSpaceRouteImport.update({
  id: '/practitioner-space',
  path: '/practitioner-space',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIdRoute = TherapistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TherapistsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssessmentRoute =
  AuthenticatedAppAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/practitioner-space': typeof PractitionerSpaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/app/assessment': typeof AuthenticatedAppAssessmentRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/practitioner-space': typeof PractitionerSpaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/app/assessment': typeof AuthenticatedAppAssessmentRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/practitioner-space': typeof PractitionerSpaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/_authenticated/app/assessment': typeof AuthenticatedAppAssessmentRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/auth'
    | '/practitioner-space'
    | '/sitemap.xml'
    | '/therapists'
    | '/app'
    | '/api/chat'
    | '/therapists/$id'
    | '/app/assessment'
    | '/app/history'
    | '/chat/$threadId'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/auth'
    | '/practitioner-space'
    | '/sitemap.xml'
    | '/therapists'
    | '/api/chat'
    | '/therapists/$id'
    | '/app/assessment'
    | '/app/history'
    | '/chat/$threadId'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/articles'
    | '/auth'
    | '/practitioner-space'
    | '/sitemap.xml'
    | '/therapists'
    | '/_authenticated/app'
    | '/api/chat'
    | '/therapists/$id'
    | '/_authenticated/app/assessment'
    | '/_authenticated/app/history'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ArticlesRoute: typeof ArticlesRoute
  AuthRoute: typeof AuthRoute
  PractitionerSpaceRoute: typeof PractitionerSpaceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TherapistsRoute: typeof TherapistsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner-space': {
      id: '/practitioner-space'
      path: '/practitioner-space'
      fullPath: '/practitioner-space'
      preLoaderRoute: typeof PractitionerSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$id': {
      id: '/therapists/$id'
      path: '/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof TherapistsIdRouteImport
      parentRoute: typeof TherapistsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assessment': {
      id: '/_authenticated/app/assessment'
      path: '/assessment'
      fullPath: '/app/assessment'
      preLoaderRoute: typeof AuthenticatedAppAssessmentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssessmentRoute: typeof AuthenticatedAppAssessmentRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssessmentRoute: AuthenticatedAppAssessmentRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TherapistsRouteChildren {
  TherapistsIdRoute: typeof TherapistsIdRoute
}

const TherapistsRouteChildren: TherapistsRouteChildren = {
  TherapistsIdRoute: TherapistsIdRoute,
}

const TherapistsRouteWithChildren = TherapistsRoute._addFileChildren(
  TherapistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ArticlesRoute: ArticlesRoute,
  AuthRoute: AuthRoute,
  PractitionerSpaceRoute: PractitionerSpaceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TherapistsRoute: TherapistsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
